apiVersion: apps/v1
kind: Deployment
metadata:
  name: rustfs-deployment
  labels:
    app: rustfs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rustfs
  template:
    metadata:
      labels:
        app: rustfs
    spec:
      containers:
        - name: rustfs
          image: rustfs/rustfs:1.0.0-rc.6
          args:
            - /data
          ports:
            - containerPort: 9000
            - containerPort: 9001
          env:
            - name: RUSTFS_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: S3_ACCESS_KEY
            - name: RUSTFS_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: S3_SECRET_KEY
            - name: RUSTFS_ADDRESS
              value: ":9000"
            - name: RUSTFS_CONSOLE_ADDRESS
              value: ":9001"
            - name: RUSTFS_CONSOLE_ENABLE
              value: "true"
            - name: RUSTFS_OBS_LOGGER_LEVEL
              value: "error"
          volumeMounts:
            - name: rustfs-persistent-storage
              mountPath: /data
      volumes:
        - name: rustfs-persistent-storage
          persistentVolumeClaim:
            claimName: rustfs-pvc
  revisionHistoryLimit: 0
