apiVersion: v1
kind: Service
metadata:
  name: rustfs-service
  labels:
    app: rustfs
spec:
  type: NodePort
  selector:
    app: rustfs
  ports:
    - name: rustfs-api
      protocol: TCP
      port: 9000
      targetPort: 9000
      nodePort: 39000
    - name: rustfs-console
      protocol: TCP
      port: 9001
      targetPort: 9001
      nodePort: 39001
